# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 11:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 29, 11, 7, 54, 324464, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
